# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#- image: 257200663051.dkr.ecr.eu-west-2.amazonaws.com/nodecircleci
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0

    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    machine: true
    steps:
      - checkout
      - run: |
          #Get all pre-requisites
          sudo apt-get update
          sudo apt-get -y install unzip python2.7 curl libpython-dev
          curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
          unzip awscli-bundle.zip
          sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

          # Login to ecr and docker login
          aws_login=`aws ecr get-login --no-include-email --region eu-west-2`
          eval $aws_login

          # Docker build, tag and push
          sudo docker build -t nodecircleci .
          sudo docker tag nodecircleci:latest 257200663051.dkr.ecr.eu-west-2.amazonaws.com/nodecircleci:latest
          sudo docker push 257200663051.dkr.ecr.eu-west-2.amazonaws.com/nodecircleci:latest

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build